### PR TITLE
Wikicom: Using WikibaseSync to create new Wikibase instance about Japanese companies

### PR DESCRIPTION
**Pull request by phucty**
This is the draft version.

[Wikicom](https://wikicom.mtab.app/wiki/Special:AllPages?from=&to=&namespace=120&hideredirects=1), [Query](https://tinyurl.com/y6ynht3b).

Imported: Init items: 1066 properties, 2059 types, 39,996 companies.

Todo: 
- Automatic sync init items with Wikidata 
- Write docs

### CODE REVIEW

**Comment by D063520** [comment]
Hi,

thank you for this pull request! : ) and sorry for taking a bit of time to review it. Could you describe a bit the main changes .... is it just refactoring, refactoring? Did you fix some bugs along the lines.

I saw that you used it for your wikibase it is great! Only that some of these specific configurations:

https://github.com/the-qa-company/WikibaseSync/pull/5/commits/33f520fbfca6328da195a1edc6a73b7a85f82739#diff-d990673708552c021fc9c73e345f846a35e8fec9da95ec07a97c0fe040b1cab6

ended up also in the pull request. These I would overwrite with the default configs from the Wikibase docker release ...

What do you think?

**Comment by phucty** [comment]
Hi @D063520

I have not finished testing the syn function yet, so this pull request is a draft, so please reject this request. 
I will replace this branch with the complete one. I am sorry for this one, but just want to let you know that I am working on this. :) 

My plan is to learn and refactor during the build of full syn features Wikibase . Then, I will back to docs, and mapping to the master branch later. 

What I did:
1. Formatter: black (sorry since many changes made in the original code)
2. Refactoring code: 
2.1. Add Enum, constants in others_config.py
2.2. Remove duplicate code in util.py: change_item_given_id... 
2.3. SPARQL query: address too many requests, and big output (using offset) in sparql_queries.py
2.4. Fixed the big number bug of PID in PropertyWikidataIdentifier
2.5. idsqarql.py --> mapper.py

Remaining errors:
- [ ] Some Wikidata languages are not accepted by Wikibase 
- [ ] Some data type are not accepted by Wikibase for example: math, lexeme, etc.

**Comment by D063520** [comment]
Ok, but maybe it would be easier if you pull one featre after the other:

- Fixed the big number bug
- Refactoring

and so on, it is easier to review and to test  ..... I think it is easier to converge towards a common code base

What do you think?

**Comment by phucty** [comment]
Thank @D063520 for your asking. 

I will pull a request to follow the common code in the master branch after I understand all the project code (could make wikicom fully syn with Wikidata). 

Since I did change many places in wikicom branch(and still working), and it is hard for you to test it now. 

I will push the wikicom branch with features tests at the end. I am sorry since I still have not finished the syn feature.

Thank you.

**Comment by D063520** [comment]
As discussed above, I will close this pull request .... I'm happy to check new ones : )

**Pull request closed without merging**
